name: C/C++ CI

on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: lint
      run: ./validate-src.sh
    - name: lint-xml
      run: sudo apt-get update && sudo apt-get install --yes libxml2-utils && ./dtd_check.sh

  build-static:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: git submodule update --init
    - name: build-static
      run: sudo docker build -t sipp-build docker && sudo docker run -v $PWD:/src sipp-build
    - uses: actions/upload-artifact@v1.0.0
      with:
         name: sipp
         path: ./sipp
